### ISSUE TITLE
高分屏下游戏会模糊

### ISSUE THREAD

**Issue by Coxxs** [ganlvtech/phaser-catch-the-cat#1]
建议考虑使用 devicePixelRatio，在高分屏下自动缩放游戏画面。

https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio

![目前效果](https://user-images.githubusercontent.com/3007303/52518297-93971200-2c83-11e9-830b-5b27f6896bd8.png)

**Comment by ganlvtech** [comment]
其实可以手动设置 canvas 的宽度和高度，这个 js 只是一个游戏的 js，具体怎么调整 canvas，可以自己使用额外的代码

**Comment by ganlvtech** [comment]
https://github.com/ganlvtech/phaser-catch-the-cat/blob/7619febd8b360e1168bc52d35a0d0a76bf37e977/public/index.html#L28

你可以看到，游戏是这样初始化的。

**Comment by ganlvtech** [comment]
@Coxxs 你有什么代码方面的建议吗？或者提交一个 Pull Request ?

**Comment by Coxxs** [comment]
我找到篇相关资料：https://supernapie.com/blog/support-retina-with-phaser-3 ，因为这个游戏用的都是 svg 素材，可能只需要稍微修改 Phaser 3 的初始化代码即可。

```javascript
let config = {
    ...
    width: window.innerWidth * window.devicePixelRatio, // set game width by multiplying window width with devicePixelRatio
    height: window.innerHeight * window.devicePixelRatio, // set game height by multiplying window height with devicePixelRatio
    ...
    zoom: 1 / window.devicePixelRatio, // Set the zoom to the inverse of the devicePixelRatio
    ...
};
```

另外为了兼容旧版浏览器，建议这样使用 window.devicePixelRatio：
```javascript
window.devicePixelRatio || 1
```

文章里还有些其他建议，可以参考下。

**Comment by ganlvtech** [comment]
Thank you.

Fixed. Please try it again. Have fun.
