### ISSUE TITLE
catch-the-cat.js能提供源吗？

### ISSUE THREAD

**Issue by XJingWei** [ganlvtech/phaser-catch-the-cat#2]
catch-the-cat.js目前是混淆的

**Comment by ganlvtech** [comment]
把项目代码下载下来，`npm install` 之后直接 `webpack`，打包的结果是未混淆的 webpack bundle

**Comment by liub1934** [comment]
项目克隆下来，`npm install`安装依赖后执行`npm run build`就能得到你想要的文件了
