### ISSUE TITLE
哪里来的声音对象啊？？？

### ISSUE THREAD

**Issue by Janet-Baker** [ganlvtech/phaser-catch-the-cat#3]
Chrome 报错：
`The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu`
所以哪里来的Audio啊？
一行代码上青天。。这代码乱的

**Comment by ganlvtech** [comment]
如果这个是 Warning 那么你可以忽略他
