### ISSUE TITLE
之前看过一个版本猫移动的时候是有一个爬过去的动作的请问怎么实现

### ISSUE THREAD

**Issue by yejiuxing** [ganlvtech/phaser-catch-the-cat#4]

**Comment by ganlvtech** [comment]
就是帧动画，每一帧的图都在这个文件夹中 https://github.com/ganlvtech/phaser-catch-the-cat/tree/master/assets/images

**Comment by ganlvtech** [comment]
还有一些数据，比如图片的顺序，图片的对齐中心等等在 https://github.com/ganlvtech/phaser-catch-the-cat/blob/master/src/data.ts 这个文件中。
