### ISSUE TITLE
如何自适应画布

### ISSUE THREAD

**Issue by zuilaoxian** [ganlvtech/phaser-catch-the-cat#7]
如果在移动端使用就会超出屏幕

**Comment by ganlvtech** [comment]
您可以尝试在 `<head></head>` 中增加

```html
<meta name="viewport" content="width=570px">
```

强制移动端的 viewport 宽度是 `570px`

**Comment by mcoo** [comment]
如何让它自适应
![image](https://user-images.githubusercontent.com/26184088/150342908-351cde8e-cfc3-4498-a3fa-ad17578c0693.png)
![U_EU RGIR}C5G2TF1}M)O6R](https://user-images.githubusercontent.com/26184088/150342940-bb751d12-d6c2-4b69-8039-a586050aad4a.png)
虽然我做了些努力 但好像还是不太行
https://mcenjoy.cn/404

**Comment by ganlvtech** [comment]
这个是你自己页面 CSS 的 overflow 的问题，你需要加一个 overflow-x: hidden

![image](https://user-images.githubusercontent.com/8651285/209472018-65865a4c-79df-4505-8db3-4dbdf80bd37c.png)
