### ISSUE TITLE
Configure difficulty

### ISSUE THREAD

**Issue by MathieuDreano** [ganlvtech/phaser-catch-the-cat#9]
Thank you for the game. My daughter enjoy it, but it is a little bit too difficult for her age.
Is it possible to chose the initial number of blocks? I see in the code that the default is 8, I'd like to add some more.
I think it would be nice to learn the game.

**Comment by ganlvtech** [comment]
You can now set `initialWallCount` to a larger value.
8 may be too difficult. And maybe it does not always have a solution.

**Comment by MathieuDreano** [comment]
Wow, nice! Thank you for releasing it so quickly !
